server:
  port: ${SERVER_PORT}

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
  application:
    name: mailPlatForm-main-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER}

